name: 'Setup Unity Editor for use with actions'
description: 'This action sets up an Unity Editor for use in actions'
author: 'pCYSl5EDgo'
inputs:
  unity-version:
    description: 'Unity version'
    required: true
  enable-cache:
    description: 'enable cache(only linux) true/false'
    required: false
  # support-webgl:
  #   description: 'Support WebGL Build'
  #   required: false
outputs:
  id:
    description: 'id'
runs:
  using: 'node12'
  main: 'dist/index.js'